# Generated by Django 2.0.7 on 2018-07-30 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('add_log', 'add'), ('detail_log', 'detail'), ('delete_log', 'delete'), ('update_log', 'update'), ('share_log', 'share'), ('attendance', 'attendance')),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名')),
                ('url', models.CharField(max_length=50, verbose_name='菜单路由')),
                ('display', models.BooleanField(default=False, verbose_name='是否显示')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='auth.Permission')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(db_index=True, max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(db_index=True, verbose_name='年龄')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
